name: 🚀 Deploy WordPress Site on Push

on: 
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy WordPress Site
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # Sync files via SFTP
    - name: 📂 Sync files via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASS }}
        protocol: sftp
        local-dir: ./  # Directory nel repository GitHub da cui prendere i file
        server-dir: /path/to/wordpress/  # Directory sul server SFTP dove caricare i file
