name: 🚀 Deploy WordPress Site on Push

on: 
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy WordPress Site
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # Sync files via SFTP
    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
